name: run-US-scraper

on:
  push:
    branches:
      - main
  schedule:
    - cron: "45 11 * * 2"  # 11:45 AM Tuesday
    - cron: "0 12 * * 2"   # 12:00 PM Tuesday
    - cron: "15 12 * * 2"  # 12:15 PM Tuesday
    - cron: "30 12 * * 2"  # 12:30 PM Tuesday
    - cron: "0 13 * * 2"   # 1:00 PM Tuesday
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr 
            any::janitor
            any::tidyr
            any::lubridate
            any::dotenv
            any::xml2
            any::jsonlite
            any::readr
            any::rvest
            any::stringr
            any::jsonlite

      - name: Set up environment variables based on DATAWRAPPR secret
        run: echo "DW_API_KEY=${{ secrets.DATAWRAPPR }}" >> $GITHUB_ENV

      - name: Install DatawRappr package
        run: |
          Rscript -e "pak::pkg_install('munichrocker/DatawRappr')"

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run script
        run: Rscript -e 'source("US_map.R")'
        
      - name: Run script
        run: Rscript -e 'source("cases.R")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add US_map.R
          git commit -m 'ran US_map.R' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
